### ISSUE TITLE
Pause/resume multiple sources using OSC?

### ISSUE THREAD

**Issue by avongrove-agtv** [mapmapteam/mapmap#444]
I need a way to be able to stop playback on multiple systems running MapMap at the same time, from the control booth (the systems running MapMap will be in a remote location).  I first thought about NDI but saw that you guys don't support that currently.  Do you have an OSC command for play/pause of video?

**Comment by aalex** [comment]
Pausing playback is possible via OSC. Currently, it is only possible to
pause all the video players at the same time. Here are the OSC messages to
do so:

* Pause: /mapmap/pause
* Play: /mapmap/play

The current list of OSC messages supported by MapMap is on this wiki page:
https://github.com/mapmapteam/mapmap/wiki/OSC

Alternatively, you could set the visibility status of each movie:

* Set visibility status: /mapmap/mapping/visible ,ii <id> <visible>

Note that OSC in MapMap is currently not working on macOS nor Windows. It
works on GNU/Linux. (I could quickly make it work on the other platforms,
but I would ideally love to be paid at least a symbolic amount in order to
do so)

About NDI support, I just opened ticket #445

**Comment by sofian** [comment]
Also, notice that sources that are not visible will automatically pause (to prevent usage of CPU). So one way to control individual playback is to enable/disable visibility of layers that use said source using OSC
```/mapmap/mapping/visible ,ii <id> <visible>```

**Comment by sofian** [comment]
I believe this has been answered.
