### ISSUE TITLE
Reorder the layer guy

### ISSUE THREAD

**Issue by skankerror** [mapmapteam/mapmap#473]
The order list of library and layers are opposite. It's a shame with large project cause most of the time media id1 might be associated to layer id1, id2 with id2 and so on. It may cause confusion

Maybe the layer order may follow a reverse order with id1 at the top, like library order

**Comment by sofian** [comment]
The IDs are created in order of the item's creation. The items themselves as they are presented in the library and layers can be re-ordered by the user. It seems to make sense that the most recently created layer appears on top of the others by default.

We need to think about this.

By the way: the IDs are not the best way to control the paints and mappings using OSC. The best is to name your layers and sources and then use OSC's regexp versions instead of IDs. If you use systematic names you can even use it to create some kinds of tags system. Eg. if you have a bunch of layers pertaining only to a certain act of a play you can name them, say "act1_left", "act1_right", "act1_ghost", "act1_cloud", etc. Then say you want to set their opacity to 0.5 you can call:
```/mapmap/mapping/opacity sf "act1_*" 0.5```

**Comment by skankerror** [comment]
If the user changes the order of the layer it changes the depth of the layers, so I agree, it's seem logical to keep actual order
Change in the library doesn't affect the final output, and user can do it in the gui, that's a solution if I want to order the 2 lists in the same way.

Yes, systemic naming, with the use of regexps can simplify controls. Thanks.

But at this time I developed a mapmap controller with cuelist here : https://gitlab.com/skankerror/MMControl and did not implement regexps yet, and I like the idea of IDs.
It only compiles on linux, and I think it's kind of punk coding, but it works for me, I can make cuelists, save them and reload them. Midi only works for my akai apcmini.

I'd love to be able to command mapmap with ossia score : https://ossia.io/ which is powerful but doesn't allow to easily send osc messages with several kind of variables.

**Comment by sofian** [comment]
Looks great! We know the people who create OSSIA I will drop them a word about compability with our software.

**Comment by sofian** [comment]
I am closing this bug for now as it seems like the current situation is acceptable.
